config/routes.rb
Rails.application.routes.draw do

  resources :quotes

  get 'welcome/index'

  resources :managers

  resources :inventories

  resources :owners

  resources :workers

  resources :sales

  resources :finances

  resources :customers

  resources :cars

  root 'welcome#index'

end

app/models/car.rb
class Car < ActiveRecord::Base

  has_many :inventories
  has_many :customer
  has_many :managers, through: :inventory
  has_one :sale
  has_many :quotes
end
def car
  @cars = Car.all
end

app/models/customer.rb
class Customer < ActiveRecord::Base

  has_many :car
  has_many :finances
  has_many :quotes
end
def self.search(search)
  where("name LIKE ?", "%#{search}%")
  end
def look_id
 @Cars = Car.all
end
def cars
  @cars = Car.all
end

app/models/finance.rb
class Finance < ActiveRecord::Base
  belongs_to :owner
  belongs_to :customer
end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
 # include ActiveModel::Model

  belongs_to :car
  belongs_to :manager
  has_many :quotes
end
def rainbow_dash
  @cars = Car.all
end
def rarity
  @managers = Manager.all
end
def spike
  @managers = Manager.all
  @managers.many?
  @inventories = @managers.many?
end
def angel
  @cars = Car.all
end

app/models/manager.rb
class Manager < ActiveRecord::Base
  has_one :inventory
  has_many :workers
end
def rarity
  @managers = Manager.all
  @managers.save
  render @managers
end

app/models/owner.rb
class Owner < ActiveRecord::Base
  has_many :finances

  end

app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :worker
  belongs_to :inventory
  belongs_to :customer
  belongs_to :car
end

def work
  @worker = Worker.all
end
def mylittlepony
  @customer = Customer.all
end
def twily
  @Cars = Car.all
end
def total_price
  self.price = (self.car.price*1.1* 1.043).round(2)
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :car
  belongs_to :customer
  belongs_to :worker

end
def car
  @cars = Car.all
end

def customer
  @customer = Customer.all
end
def worker
  @worker = Worker.all
end

app/models/worker.rb
class Worker < ActiveRecord::Base
  belongs_to :manager
  has_many :quotes
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  #include ActionView::Helpers::NumberHelper
  before_action :set_car, only: [:show, :edit, :update, :destroy]


  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:brand, :model, :vin, :msrp, :price, :acquired, :sold)
    end
    def pony
      @car = Item.find(params[:id])
    end
end

app/controllers/finances_controller.rb
class FinancesController < ApplicationController
  before_action :set_finance, only: [:show, :edit, :update, :destroy]

  # GET /finances
  # GET /finances.json
  def index
    @finances = Finance.all
  end

  # GET /finances/1
  # GET /finances/1.json
  def show
  end

  # GET /finances/new
  def new
    @finance = Finance.new
  end

  # GET /finances/1/edit
  def edit
  end

  # POST /finances
  # POST /finances.json
  def create
    @finance = Finance.new(finance_params)

    respond_to do |format|
      if @finance.save
        format.html { redirect_to @finance, notice: 'Finance was successfully created.' }
        format.json { render :show, status: :created, location: @finance }
      else
        format.html { render :new }
        format.json { render json: @finance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /finances/1
  # PATCH/PUT /finances/1.json
  def update
    respond_to do |format|
      if @finance.update(finance_params)
        format.html { redirect_to @finance, notice: 'Finance was successfully updated.' }
        format.json { render :show, status: :ok, location: @finance }
      else
        format.html { render :edit }
        format.json { render json: @finance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /finances/1
  # DELETE /finances/1.json
  def destroy
    @finance.destroy
    respond_to do |format|
      format.html { redirect_to finances_url, notice: 'Finance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_finance
      @finance = Finance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def finance_params
      params.require(:finance).permit(:sai, :ppy, :year)
    end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:customer_id, :car_id, :worker_id, :sold)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end
def aloe(price)
  number_to_currency(price, precision:1 )
end

app/helpers/customers_helper.rb
module CustomersHelper
end
def finance(boolean)
  boolean ? 'Yes' : 'No'

  false.humanize
  # => "Yes"

  false.humanize
  # => "No"
end

app/helpers/finances_helper.rb
module FinancesHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/finances/_form.html.erb
<%= form_for(@finance) do |f| %>
  <% if @finance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@finance.errors.count, "error") %> prohibited this finance from being saved:</h2>

      <ul>
      <% @finance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'Simple Annual Interest'%>
    <%= f.label :sai do %><br>
    <%= f.text_field :sai %>
        <% end %>
  </div>
  <div class="field">
    <%= f.label 'Payments Per Year'%>
    <%= f.label :ppy do %><br>
    <%= f.number_field :ppy %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label 'Years selected'%>
    <%= f.label :year do %><br>
    <%= f.number_field :year %>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/finances/edit.html.erb
<h1>Editing Finance</h1>

<%= render 'form' %>

<%= link_to 'Show', @finance %> |
<%= link_to 'Back', finances_path %>

app/views/finances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customer Financing Table</h1>

<table>
  <thead>
    <tr>
      <th>Simple Annual Interest</th>
      <th>Payments per Year</th>
      <th>Years Chosen</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @finances.each do |finance| %>
      <tr>
        <td><%= number_to_percentage(finance.sai) %></td>
        <td><%= finance.ppy %></td>
        <td><%= finance.year %></td>
        <td><%= link_to 'Show', finance %></td>
        <td><%= link_to 'Edit', edit_finance_path(finance) %></td>
        <td><%= link_to 'Destroy', finance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Finance', new_finance_path %>
<br> </br>
<%= link_to 'Back To Home Page', welcome_index_path %>

app/views/finances/new.html.erb
<h1>New Finance</h1>

<%= render 'form' %>

<%= link_to 'Back', finances_path %>

app/views/finances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sai:</strong>
  <%= number_to_percentage(@finance.sai) %>
</p>

<p>
  <strong>Ppy:</strong>
  <%= @finance.ppy %>
</p>

<p>
  <strong>Year:</strong>
  <%= @finance.year %>
</p>

<%= link_to 'Edit', edit_finance_path(@finance) %> |
<%= link_to 'Back', finances_path %>