config/routes.rb
Rails.application.routes.draw do

  resources :quotes

  get 'welcome/index'

  resources :managers

  resources :inventories

  resources :owners

  resources :workers

  resources :sales

  resources :finances

  resources :customers

  resources :cars

  root 'welcome#index'

end

app/models/car.rb
class Car < ActiveRecord::Base

  has_many :inventories
  has_many :customer
  has_many :managers, through: :inventory
  has_one :sale
  has_many :quotes
end
def car
  @cars = Car.all
end

app/models/customer.rb
class Customer < ActiveRecord::Base

  has_many :car
  has_many :finances
  has_many :quotes
end
def self.search(search)
  where("name LIKE ?", "%#{search}%")
  end
def look_id
 @Cars = Car.all
end
def cars
  @cars = Car.all
end

app/models/finance.rb
class Finance < ActiveRecord::Base
  belongs_to :owner
  belongs_to :customer
end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
 # include ActiveModel::Model

  belongs_to :car
  belongs_to :manager
  has_many :quotes
end
def rainbow_dash
  @cars = Car.all
end
def rarity
  @managers = Manager.all
end
def spike
  @managers = Manager.all
  @managers.many?
  @inventories = @managers.many?
end
def angel
  @cars = Car.all
end

app/models/manager.rb
class Manager < ActiveRecord::Base
  has_one :inventory
  has_many :workers
end
def rarity
  @managers = Manager.all
  @managers.save
  render @managers
end

app/models/owner.rb
class Owner < ActiveRecord::Base
  has_many :finances

  end

app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :worker
  belongs_to :inventory
  belongs_to :customer
  belongs_to :car
end

def work
  @worker = Worker.all
end
def mylittlepony
  @customer = Customer.all
end
def twily
  @Cars = Car.all
end
def total_price
  self.price = (self.car.price*1.1* 1.043).round(2)
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :car
  belongs_to :customer
  belongs_to :worker

end
def car
  @cars = Car.all
end

def customer
  @customer = Customer.all
end
def worker
  @worker = Worker.all
end

app/models/worker.rb
class Worker < ActiveRecord::Base
  belongs_to :manager
  has_many :quotes
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  #include ActionView::Helpers::NumberHelper
  before_action :set_car, only: [:show, :edit, :update, :destroy]


  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:brand, :model, :vin, :msrp, :price, :acquired, :sold)
    end
    def pony
      @car = Item.find(params[:id])
    end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.all
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:worker_id, :customer_id, :car_id, :price, :sale_tax, :total_price, :quote_status)
    end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:customer_id, :car_id, :worker_id, :sold)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end
def aloe(price)
  number_to_currency(price, precision:1 )
end

app/helpers/customers_helper.rb
module CustomersHelper
end
def finance(boolean)
  boolean ? 'Yes' : 'No'

  false.humanize
  # => "Yes"

  false.humanize
  # => "No"
end

app/helpers/finances_helper.rb
module FinancesHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/quotes/_form.html.erb
<%= form_for(@quote) do |f| %>
  <% if @quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% @quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :worker_id %><br>
    <%= f.collection_select :worker_id, Worker.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :customer_id %><br>
    <%= f.collection_select :customer_id, Customer.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :car_id %><br>
    <%= f.collection_select :car_id, Car.all, :id, :model %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :sale_tax %><br>
    <%= f.text_field :sale_tax, :value => 4.3 ,:class => 'form' %>
  </div>
  <div class="field">
    <%= f.label :total_price %><br>
    <%= f.text_field :total_price %>
  </div>
  <div class="field">
    <%= f.label 'Sold ?' %>
    <%= f.label :quote_status do %><br>
    <%= f.check_box :quote_status, {}, "Yes", "No"%>
        No
        <%= f.check_box :quote_status, {}, "Yes", "No"%>
        Yes
        <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quotes/edit.html.erb
<h1>Editing Quote</h1>

<%= render 'form' %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Quotes</h1>

<table>
  <thead>
    <tr>
      <th>Sales Rep</th>
      <th>Customer</th>
      <th>Car</th>
      <th>Price</th>
      <th>Sales Tax</th>
      <th>Total price</th>
      <th>Quote Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quotes.each do |quote| %>
      <tr>
        <td><%= quote.worker.name %></td>
        <td><%= quote.customer.name %></td>
        <td><%= quote.car.model %></td>
        <td><%= number_to_currency(quote.price) %></td>
        <td><%= number_to_percentage(quote.sale_tax) %></td>
        <td><%= number_to_currency(quote.total_price) %></td>
        <td><%= quote.quote_status %></td>
        <td><%= link_to 'Show', quote %></td>
        <td><%= link_to 'Edit', edit_quote_path(quote) %></td>
        <td><%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quote', new_quote_path %>
<br> </br>
<%= link_to 'Back To Home Page', welcome_index_path %>

app/views/quotes/new.html.erb
<h1>New Quote</h1>

<%= render 'form' %>

<%= link_to 'Back', quotes_path %>

app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Worker:</strong>
  <%= @quote.worker_id %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @quote.customer_id %>
</p>

<p>
  <strong>Car:</strong>
  <%= @quote.car_id %>
</p>

<p>
  <strong>Price:</strong>
  <%= @quote.price %>
</p>

<p>
  <strong>Sale tax:</strong>
  <%= @quote.sale_tax %>
</p>

<p>
  <strong>Total price:</strong>
  <%= @quote.total_price %>
</p>

<p>
  <strong>Quote status:</strong>
  <%= @quote.quote_status %>
</p>

<%= link_to 'Edit', edit_quote_path(@quote) %> |
<%= link_to 'Back', quotes_path %>