config/routes.rb
Rails.application.routes.draw do

  resources :quotes

  get 'welcome/index'

  resources :managers

  resources :inventories

  resources :owners

  resources :workers

  resources :sales

  resources :finances

  resources :customers

  resources :cars

  root 'welcome#index'

end

app/models/car.rb
class Car < ActiveRecord::Base

  has_many :inventories
  has_many :customer
  has_many :managers, through: :inventory
  has_one :sale
  has_many :quotes
end
def car
  @cars = Car.all
end

app/models/customer.rb
class Customer < ActiveRecord::Base

  has_many :car
  has_many :finances
  has_many :quotes
end
def self.search(search)
  where("name LIKE ?", "%#{search}%")
  end
def look_id
 @Cars = Car.all
end
def cars
  @cars = Car.all
end

app/models/finance.rb
class Finance < ActiveRecord::Base
  belongs_to :owner
  belongs_to :customer
end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
 # include ActiveModel::Model

  belongs_to :car
  belongs_to :manager
  has_many :quotes
end
def rainbow_dash
  @cars = Car.all
end
def rarity
  @managers = Manager.all
end
def spike
  @managers = Manager.all
  @managers.many?
  @inventories = @managers.many?
end
def angel
  @cars = Car.all
end

app/models/manager.rb
class Manager < ActiveRecord::Base
  has_one :inventory
  has_many :workers
end
def rarity
  @managers = Manager.all
  @managers.save
  render @managers
end

app/models/owner.rb
class Owner < ActiveRecord::Base
  has_many :finances

  end

app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :worker
  belongs_to :inventory
  belongs_to :customer
  belongs_to :car
end

def work
  @worker = Worker.all
end
def mylittlepony
  @customer = Customer.all
end
def twily
  @Cars = Car.all
end
def total_price
  self.price = (self.car.price*1.1* 1.043).round(2)
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :car
  belongs_to :customer
  belongs_to :worker

end
def car
  @cars = Car.all
end

def customer
  @customer = Customer.all
end
def worker
  @worker = Worker.all
end

app/models/worker.rb
class Worker < ActiveRecord::Base
  belongs_to :manager
  has_many :quotes
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  #include ActionView::Helpers::NumberHelper
  before_action :set_car, only: [:show, :edit, :update, :destroy]


  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:brand, :model, :vin, :msrp, :price, :acquired, :sold)
    end
    def pony
      @car = Item.find(params[:id])
    end
end

app/controllers/managers_controller.rb
class ManagersController < ApplicationController
  before_action :set_manager, only: [:show, :edit, :update, :destroy]

  # GET /managers
  # GET /managers.json
  def index
    @managers = Manager.all
  end

  # GET /managers/1
  # GET /managers/1.json
  def show
  end

  # GET /managers/new
  def new
    @manager = Manager.new
  end

  # GET /managers/1/edit
  def edit
  end

  # POST /managers
  # POST /managers.json
  def create
    @manager = Manager.new(manager_params)

    respond_to do |format|
      if @manager.save
        format.html { redirect_to @manager, notice: 'Manager was successfully created.' }
        format.json { render :show, status: :created, location: @manager }
      else
        format.html { render :new }
        format.json { render json: @manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /managers/1
  # PATCH/PUT /managers/1.json
  def update
    respond_to do |format|
      if @manager.update(manager_params)
        format.html { redirect_to @manager, notice: 'Manager was successfully updated.' }
        format.json { render :show, status: :ok, location: @manager }
      else
        format.html { render :edit }
        format.json { render json: @manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /managers/1
  # DELETE /managers/1.json
  def destroy
    @manager.destroy
    respond_to do |format|
      format.html { redirect_to managers_url, notice: 'Manager was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manager
      @manager = Manager.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def manager_params
      params.require(:manager).permit(:name, :department, :hire_date)
    end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:customer_id, :car_id, :worker_id, :sold)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end
def aloe(price)
  number_to_currency(price, precision:1 )
end

app/helpers/customers_helper.rb
module CustomersHelper
end
def finance(boolean)
  boolean ? 'Yes' : 'No'

  false.humanize
  # => "Yes"

  false.humanize
  # => "No"
end

app/helpers/finances_helper.rb
module FinancesHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/managers/_form.html.erb
<%= form_for(@manager) do |f| %>
  <% if @manager.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@manager.errors.count, "error") %> prohibited this manager from being saved:</h2>

      <ul>
      <% @manager.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :department %><br>
    <%= f.text_field :department %>
  </div>
  <div class="field">
    <%= f.label :hire_date %><br>
    <%= f.date_select :hire_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/managers/edit.html.erb
<h1>Editing Manager</h1>

<%= render 'form' %>

<%= link_to 'Show', @manager %> |
<%= link_to 'Back', managers_path %>

app/views/managers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Managers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Department</th>
      <th>Hire date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @managers.each do |manager| %>
      <tr>
        <td><%= manager.name %></td>
        <td><%= manager.department %></td>
        <td><%= manager.hire_date %></td>
        <td><%= link_to 'Show', manager %></td>
        <td><%= link_to 'Edit', edit_manager_path(manager) %></td>
        <td><%= link_to 'Destroy', manager, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Manager', new_manager_path %>
<br> </br>
<%= link_to 'Back To Home Page', welcome_index_path %>

app/views/managers/new.html.erb
<h1>New Manager</h1>

<%= render 'form' %>

<%= link_to 'Back', managers_path %>

app/views/managers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @manager.name %>
</p>

<p>
  <strong>Department:</strong>
  <%= @manager.department %>
</p>

<p>
  <strong>Hire date:</strong>
  <%= @manager.hire_date %>
</p>

<%= link_to 'Edit', edit_manager_path(@manager) %> |
<%= link_to 'Back', managers_path %>