config/routes.rb
Rails.application.routes.draw do

  resources :quotes

  get 'welcome/index'

  resources :managers

  resources :inventories

  resources :owners

  resources :workers

  resources :sales

  resources :finances

  resources :customers

  resources :cars

  root 'welcome#index'

end

app/models/car.rb
class Car < ActiveRecord::Base

  has_many :inventories
  has_many :customer
  has_many :managers, through: :inventory
  has_one :sale
  has_many :quotes
end
def car
  @cars = Car.all
end

app/models/customer.rb
class Customer < ActiveRecord::Base

  has_many :car
  has_many :finances
  has_many :quotes
end
def self.search(search)
  where("name LIKE ?", "%#{search}%")
  end
def look_id
 @Cars = Car.all
end
def cars
  @cars = Car.all
end

app/models/finance.rb
class Finance < ActiveRecord::Base
  belongs_to :owner
  belongs_to :customer
end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
 # include ActiveModel::Model

  belongs_to :car
  belongs_to :manager
  has_many :quotes
end
def rainbow_dash
  @cars = Car.all
end
def rarity
  @managers = Manager.all
end
def spike
  @managers = Manager.all
  @managers.many?
  @inventories = @managers.many?
end
def angel
  @cars = Car.all
end

app/models/manager.rb
class Manager < ActiveRecord::Base
  has_one :inventory
  has_many :workers
end
def rarity
  @managers = Manager.all
  @managers.save
  render @managers
end

app/models/owner.rb
class Owner < ActiveRecord::Base
  has_many :finances

  end

app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :worker
  belongs_to :inventory
  belongs_to :customer
  belongs_to :car
end

def work
  @worker = Worker.all
end
def mylittlepony
  @customer = Customer.all
end
def twily
  @Cars = Car.all
end
def total_price
  self.price = (self.car.price*1.1* 1.043).round(2)
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :car
  belongs_to :customer
  belongs_to :worker

end
def car
  @cars = Car.all
end

def customer
  @customer = Customer.all
end
def worker
  @worker = Worker.all
end

app/models/worker.rb
class Worker < ActiveRecord::Base
  belongs_to :manager
  has_many :quotes
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  #include ActionView::Helpers::NumberHelper
  before_action :set_car, only: [:show, :edit, :update, :destroy]


  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:brand, :model, :vin, :msrp, :price, :acquired, :sold)
    end
    def pony
      @car = Item.find(params[:id])
    end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  before_action :set_owner, only: [:show, :edit, :update, :destroy]

  # GET /owners
  # GET /owners.json
  def index
    @owners = Owner.all
  end

  # GET /owners/1
  # GET /owners/1.json
  def show
  end

  # GET /owners/new
  def new
    @owner = Owner.new
  end

  # GET /owners/1/edit
  def edit
  end

  # POST /owners
  # POST /owners.json
  def create
    @owner = Owner.new(owner_params)

    respond_to do |format|
      if @owner.save
        format.html { redirect_to @owner, notice: 'Owner was successfully created.' }
        format.json { render :show, status: :created, location: @owner }
      else
        format.html { render :new }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /owners/1
  # PATCH/PUT /owners/1.json
  def update
    respond_to do |format|
      if @owner.update(owner_params)
        format.html { redirect_to @owner, notice: 'Owner was successfully updated.' }
        format.json { render :show, status: :ok, location: @owner }
      else
        format.html { render :edit }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /owners/1
  # DELETE /owners/1.json
  def destroy
    @owner.destroy
    respond_to do |format|
      format.html { redirect_to owners_url, notice: 'Owner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_owner
      @owner = Owner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def owner_params
      params.require(:owner).permit(:total_gross_revenue, :net_profit, :sales_tax_total)
    end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:customer_id, :car_id, :worker_id, :sold)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end
def aloe(price)
  number_to_currency(price, precision:1 )
end

app/helpers/customers_helper.rb
module CustomersHelper
end
def finance(boolean)
  boolean ? 'Yes' : 'No'

  false.humanize
  # => "Yes"

  false.humanize
  # => "No"
end

app/helpers/finances_helper.rb
module FinancesHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/cars/_form.html.erb
<%= form_for(@car) do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :brand %><br>
    <%= f.text_field :brand %>
  </div>
  <div class="field">
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :vin %><br>
    <%= f.number_field :vin %>
  </div>
  <div class="field">
    <%= f.label :msrp %><br>
    <%= f.text_field :msrp %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :acquired %><br>
    <%= f.date_select :acquired %>
  </div>
  <div class="field">
    <%= f.label :sold %><br>
    <%= f.date_select :sold %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form' %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cars</h1>

<table>
  <thead>
    <tr>
      <th>Brand</th>
      <th>Model</th>
      <th>Vin</th>
      <th>Msrp</th>
      <th>Price</th>
      <th>Acquired</th>
      <th>Sold</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.brand %></td>
        <td><%= car.model %></td>
        <td><%= car.vin %></td>
        <td><%= number_to_currency(car.msrp) %></td>
        <td><%= number_to_currency(car.price) %></td>
        <td><%= car.acquired %></td>
        <td><%= car.sold %></td>
        <td><%= link_to 'Show', car %></td>
        <td><%= link_to 'Edit', edit_car_path(car) %></td>
        <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Car', new_car_path %>
<br> </br>
<%= link_to 'Back To Home Page', welcome_index_path %>

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form' %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Brand:</strong>
  <%= @car.brand %>
</p>

<p>
  <strong>Model:</strong>
  <%= @car.model %>
</p>

<p>
  <strong>Vin:</strong>
  <%= @car.vin %>
</p>

<p>
  <strong>Msrp:</strong>
  <%= @car.msrp  %>
</p>

<p>
  <strong>Price:</strong>
  <%= @car.price %>
</p>

<p>
  <strong>Acquired:</strong>
  <%= @car.acquired %>
</p>

<p>
  <strong>Sold:</strong>
  <%= @car.sold %>
</p>


<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>

app/views/owners/_form.html.erb
<%= form_for(@owner) do |f| %>
  <% if @owner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@owner.errors.count, "error") %> prohibited this owner from being saved:</h2>

      <ul>
      <% @owner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :total_gross_revenue %><br>
    <%= f.number_field :total_gross_revenue %>
  </div>
  <div class="field">
    <%= f.label :net_profit %><br>
    <%= f.number_field :net_profit %>
  </div>
  <div class="field">
    <%= f.label :sales_tax_total %><br>
    <%= f.number_field :sales_tax_total %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/owners/edit.html.erb
<h1>Editing Financial Information</h1>

<%= render 'form' %>

<%= link_to 'Show', @owner %> |
<%= link_to 'Back', owners_path %>

app/views/owners/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Financial Information for Compylight Auto</h1>

<table>
  <thead>
    <tr>
      <th>Total gross revenue</th>
      <th>Net profit</th>
      <th>Sales tax total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @owners.each do |owner| %>
      <tr>
        <td><%= number_to_currency(owner.total_gross_revenue) %></td>
        <td><%= number_to_currency(owner.net_profit) %></td>
        <td><%= number_to_percentage(owner.sales_tax_total) %></td>
        <td><%= link_to 'Show', owner %></td>
        <td><%= link_to 'Edit', edit_owner_path(owner) %></td>
        <td><%= link_to 'Destroy', owner, method: :delete, data: { confirm: 'Are you sure?, Data will be lost !' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Create Financial Report', new_owner_path %>
<br> </br>
<%= link_to 'Back To Home Page', welcome_index_path %>

app/views/owners/new.html.erb
<h1>Financial Information</h1>

<%= render 'form' %>

<%= link_to 'Back', owners_path %>

app/views/owners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Total gross revenue:</strong>
  <%= @owner.total_gross_revenue %>
</p>

<p>
  <strong>Net profit:</strong>
  <%= @owner.net_profit %>
</p>

<p>
  <strong>Sales tax total:</strong>
  <%= @owner.sales_tax_total %>
</p>

<%= link_to 'Edit', edit_owner_path(@owner) %> |
<%= link_to 'Back', owners_path %>

app/views/sales/_form.html.erb
<%= form_for(@sale) do |f| %>
  <% if @sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% @sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :customer_id %><br>
    <%= f.collection_select :customer_id, Customer.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :car_id %><br>
    <%= f.collection_select :car_id, Car.all, :id, :model %>
  </div>
  <div class="field">
    <%= f.label :worker_id %><br>
    <%= f.collection_select :worker_id, Worker.all, :id, :name  %>
  </div>
  <div class="field">
    <%= f.label 'Sold Price'%>
    <%= f.label :sold do %><br>
    <%= f.text_field :sold %>
        <%end%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sales/edit.html.erb
<h1>Editing Sale</h1>

<%= render 'form' %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employee Sales</h1>

<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th>Car</th>
      <th>Worker</th>
      <th>Sold</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= sale.customer.name %></td>
        <td><%= sale.car.model %></td>
        <td><%= sale.worker.name %></td>
        <td><%= number_to_currency(sale.sold) %></td>
        <td><%= link_to 'Show', sale %></td>
        <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
        <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sale', new_sale_path %>
<br> </br>
<%= link_to 'Back To Home Page', welcome_index_path %>

app/views/sales/new.html.erb
<h1>New Sale</h1>

<%= render 'form' %>

<%= link_to 'Back', sales_path %>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @sale.customer_id %>
</p>

<p>
  <strong>Car:</strong>
  <%= @sale.car_id %>
</p>

<p>
  <strong>Worker:</strong>
  <%= @sale.worker_id %>
</p>

<p>
  <strong>Sold Price:</strong>
  <%= @sale.sold %>
</p>

<%= link_to 'Edit', edit_sale_path(@sale) %> |
<%= link_to 'Back', sales_path %>